name: PS Ford Photography
favicon: null
layout_spectrum: 0.9246689837891608
typography_spectrum: 0.5302803632803261
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5625
  lightness: 0.998429182684049
  saturation: 0.5444439612329006
  rhythmicContrast: 0.7134456257335842
purpose: []
